module Opal.Distance.Stations (
    Station(..),
    stations
) where

data Station
    = Artarmon
    | Ashfield
    | Asquith
    | Auburn
    | Beecroft
    | Berowra
    | Blacktown
    | BondiJunction
    | Burwood
    | Cabramatta
    | Camellia
    | CanleyVale
    | Carlingford
    | Casula
    | Central
    | Chatswood
    | Cheltenham
    | CircularQuay
    | Clarendon
    | Clyde
    | ConcordWest
    | Cowan
    | Croydon
    | Denistone
    | Doonside
    | Dundas
    | EastRichmond
    | Eastwood
    | Edgecliff
    | EmuPlains
    | Epping
    | Fairfield
    | Flemington
    | Gordon
    | Gosford
    | Granville
    | Guildford
    | HarrisPark
    | HawkesburyRiver
    | Homebush
    | Hornsby
    | Killara
    | KingsCross
    | Kingswood
    | Koolewong
    | Lewisham
    | Lidcombe
    | Lindfield
    | Lisarow
    | Liverpool
    | Macdonaldtown
    | MacquariePark
    | MacquarieUniversity
    | Marayong
    | MartinPlace
    | Meadowbank
    | Merrylands
    | MilsonsPoint
    | MountColah
    | MountDruitt
    | MountKuringGai
    | Mulgrave
    | Museum
    | Narara
    | Newtown
    | NiagaraPark
    | Normanhurst
    | NorthRyde
    | NorthStrathfield
    | NorthSydney
    | OlympicPark
    | Ourimbah
    | Parramatta
    | PendleHill
    | PennantHills
    | Penrith
    | Petersham
    | PointClare
    | Pymble
    | QuakersHill
    | Redfern
    | Rhodes
    | Richmond
    | Riverstone
    | RootyHill
    | Rosehill
    | Roseville
    | Rydalmere
    | Schofields
    | SevenHills
    | StJames
    | StLeonards
    | StMarys
    | Stanmore
    | Strathfield
    | SummerHill -- TBA at https://www.opal.com.au/en/about-opal/what-services-can-i-use-it-on/Train_stations_with_opal/
    | Tascott
    | Telopea
    | Thornleigh
    | Toongabbie
    | TownHall
    | Tuggerah
    | Turramurra
    | Vineyard
    | Wahroonga
    | Waitara
    | Warrawee
    | WarwickFarm
    | Waverton
    | Wentworthville
    | Werrington
    | WestRyde
    | Westmead
    | Windsor
    | Wollstonecraft
    | Wondobyne
    | WoyWoy
    | Wynyard
    | Wyong
    | Yennora
    deriving (Bounded, Eq, Enum, Ord, Read, Show)

stations :: [Station]
stations = [(minBound :: Station) ..]
